name: Build and Test Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: docker build -t myapp:test .

      - name: Run container and wait for readiness
        run: |
          docker run --name test-container -d -p 8080:8080 myapp:test

          for i in $(seq 1 30); do
              status_code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1:8080/api/v1/users/all)
              if [ "$status_code" -eq 200 ]; then
                echo "Application endpoint is ready with status 200"
                break
              fi
                echo "Waiting for application to return 200..."
                sleep 1
          done
  
          docker stop test-container
          docker rm test-container
          docker image rm myapp:test
