name: Build and Test Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run tests with Maven
        run: mvn test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        id: build_image
        run: |
          docker build --file Dockerfile --tag myapp:test .

      - name: Run container and verify
        run: |
          docker run --name test-container -d myapp:test
          
          docker ps | grep test-container

          docker exec test-container some-test-command

          docker stop test-container
          docker rm test-container