name: Build, Run and Test Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean package -DskipTests


      - name: Build Docker images
        run: docker-compose build

      - name: Start services
        run: docker-compose up -d

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend to start..."
          for i in {1..15}; do
            if curl -s http://127.0.0.1:8080/api/v1/users/all | grep UP; then
              echo "Backend is up!"
              break
            fi
            sleep 1
          done

      - name: Test backend endpoints
        run: |
          curl -v http://127.0.0.1:8080/swagger-ui/index.html
          curl -v http://127.0.0.1:8080/api/v1/users/all

      - name: Stop services
        run: docker-compose down
