name: Build and Test Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        id: build_image
        run: |
          mvn clean package
          docker build --file Dockerfile --tag myapp:test .

      - name: Run container and verify
        run: |
          docker run --name test-container -d myapp:test
          
          docker ps | grep test-container

          docker exec test-container some-test-command

          docker stop test-container
          docker rm test-container